Feature/gsheet parse
TheIOFoundation/ProjectLockdown pull request #414
Opened 2021-07-28 11:48 UTC by YehualashetGit

2021-07-31 10:19 UTC, daphnecys requested changes
API/src/app/DataSetLayer/dto/dataSetLayer.dto.ts createAt() and updatedAt() are using different tenses. Suggest change createAt() to createdAt().

2021-08-03 09:18 UTC, YehualashetGit commented
> API/src/app/DataSetLayer/dto/dataSetLayer.dto.ts createAt() and updatedAt() are using different tenses. Suggest change createAt() to createdAt().

done

2021-08-11 13:21 UTC, Mirdrack commented
Terraform fix.
Add the new blank line in one file to trigger the rebuild the PR and it should ignore the Terraform configuration.
Let me know if this doesn't work.

2021-08-19 14:12 UTC, daphnecys approved these changes

2021-08-19 14:22 UTC, merged